### ISSUE TITLE
one-to-many relationship with comment symfony2

### ISSUE THREAD

**Issue by youssfisebti** [sonata-project/SonataCommentBundle#26]
I want to link my entity with a comment but I can't find a documentation or an example for this.

I have an Entity Product that I want to associate with a simple comment with the Sonata Comment Bundle.

I use it in my template like this:

```
{{ sonata_block_render_event('sonata.comment', {'id': 'my-custom-thread-identifier}) }}
```

**Comment by core23** [comment]
That's right @youssfisebti . You have to render the comment block in your template:

```
{{ sonata_block_render_event('sonata.comment', {'id': 'my-custom-thread-identifier_' ~ entity.id }) }}
```
