### ISSUE TITLE
Should we deprecate this bundle ? 

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataCommentBundle#299]
## Feature Request

FOSCommentBundle seems abandonned: https://github.com/FriendsOfSymfony/FOSCommentBundle/issues/715

Should we deprecate/abandon this package then ? @sonata-project/contributors

In our case, it's only used by the sandbox and the ecommerce repository.

**Comment by VincentLanglet** [comment]
This bundle is abandoned

**Comment by wbloszyk** [comment]
This bundle is used in `ecommerce` only. If `ecommerce` is abandoned then this bundle should be too.

**Comment by VincentLanglet** [comment]
> This bundle is used in `ecommerce` only. If `ecommerce` is abandoned then this bundle should be too.

Already done https://github.com/sonata-project/SonataCommentBundle/issues/328
