### ISSUE TITLE
Invalid type for path "sonata_comment.notes.values". Expected scalar, but got array.

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/SonataCommentBundle#33]
Configuration.php says
```php
       ->scalarNode('values')->defaultValue(array(1, 2, 3, 4, 5))->end()
```
Shouldn't it be
```php
       ->arrayNode('values')
               ->prototype('scalar')->end()
               ->defaultValue(array(1, 2, 3, 4, 5))
        ->end()?
```

if I try to use as reference configuration what I get from "config:dump-reference SonataCommentBundle --format=yaml", I get the above exception whereas the proposed evolution seems to work ...

By the way, the "given note" displayed is not the array value but the index, so that, currently, when you select "1" you get "given note: 0" ...

**Comment by core23** [comment]
Can you provide a PR for this @stphnpt

**Comment by stphnpt** [comment]
Configuration for notes #36
